apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp
  labels:
    app: backend-restapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-restapp
  template:
    metadata:
      labels:
        app: backend-restapp
        tier: backend
    spec:
      containers:
      - name: backend-restapp
        image: stacksimplify/kube-helloworld:1.0.0
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service ## VERY VERY IMPORTANT - NGINX PROXYPASS needs this name only
  labels:
    app: backend-restapp
    tier: backend
spec:
  #type: ClusterIP is a default service in k8s
  selector:
    app: backend-restapp
  ports:
  - name: http
    port: 8080 # ClusterIP Service Port
    targetPort: 8080 # Container Port


